import type { LodgingLandingConfig } from './lodging-types'

export const defaultConfig: LodgingLandingConfig = {
  hero: {
    tagline: 'Donde el tiempo se detiene y el Pirineo susurra',
    locationText: 'Aínsa · Huesca, Aragón',
    propertyType: 'Hotel Rural',
    badges: [
      { id: 'b1', text: 'Imprescindible LPMBE' },
      { id: 'b2', text: 'Selección 2024' },
    ],
  },
  quickStats: {
    items: [
      { id: 'qs1', icon: 'clock',    label: 'Check-in / Check-out', value: '15:00 — 12:00' },
      { id: 'qs2', icon: 'bed',      label: 'Habitaciones',         value: '8 estancias' },
      { id: 'qs3', icon: 'banknote', label: 'Desde',                value: '120 €/noche' },
      { id: 'qs4', icon: 'star',     label: 'Valoración media',     value: '4.8 / 5' },
      { id: 'qs5', icon: 'calendar', label: 'Renovado',             value: '2019' },
    ],
  },
  story: {
    eyebrow: 'Nuestra historia',
    title: 'Una casona del siglo XVIII\ndevuelta a la vida',
    paragraphs: [
      'Enclavada en el corazón medieval de Aínsa, la Posada del Sobrarbe nació de la pasión de la familia Castán por preservar el patrimonio vivo del Pirineo. Lo que en el siglo XVIII fue una imponente casa señorial de piedra es hoy un refugio de ocho habitaciones donde cada recoveco guarda su propia historia.',
      'La rehabilitación, iniciada en 2017 y culminada en 2019, respetó escrupulosamente las bóvedas de sillería, las vigas originales de roble y los arcos de medio punto, añadiendo con mesura el confort que los viajeros contemporáneos merecen.',
      'Desde la terraza panorámica, las cumbres del Cotiella y el Turbón marcan el horizonte al amanecer. En el comedor de vigas, el desayuno se convierte en un ceremonial con miel del Sobrarbe, pan de masa madre y quesos artesanos.',
    ],
    pullQuote: 'Donde el tiempo se detiene y la naturaleza susurra en cada piedra.',
  },
  rooms: {
    eyebrow: 'Nuestras estancias',
    title: 'Ocho formas de dormir\nentre piedra y montaña',
    items: [
      {
        id: 'r1',
        name: 'Habitación Superior Pirenaica',
        description: 'Vistas panorámicas al Cotiella, vigas de roble y bañera exenta de cobre en el baño.',
        guests: 2,
        beds: 'Cama king',
        price: 'Desde 165 €/noche',
        imageUrl: '/images/room-1.jpg',
      },
      {
        id: 'r2',
        name: 'Junior Suite El Sobrarbe',
        description: 'El mayor espacio del hotel: sala de estar independiente, chimenea y terraza privada.',
        guests: 2,
        beds: 'Cama king',
        price: 'Desde 220 €/noche',
        imageUrl: '/images/room-2.jpg',
      },
      {
        id: 'r3',
        name: 'Estancia Familiar con Buhardilla',
        description: 'Planta baja con acceso directo al jardín y altillo con dos camas para los más pequeños.',
        guests: 4,
        beds: '1 matrimonio + 2 individuales',
        price: 'Desde 195 €/noche',
        imageUrl: '/images/room-3.jpg',
      },
      {
        id: 'r4',
        name: 'Habitación Clásica Medieval',
        description: 'El espíritu original de la casona: bóvedas de sillería, suelo de terracota y luz suave.',
        guests: 2,
        beds: 'Cama queen',
        price: 'Desde 120 €/noche',
        imageUrl: '/images/hero-2.jpg',
      },
    ],
  },
  experiences: {
    eyebrow: 'Experiencias',
    title: '¿Qué harás durante tu escapada?',
    items: [
      {
        id: 'e1',
        title: 'Senderismo por el Cañón de Añisclo',
        description: 'Recorrido guiado por uno de los cañones más espectaculares de los Pirineos, con paradas en miradores exclusivos y flora endémica.',
        duration: '5 h',
        badge: 'Incluido',
        imageUrl: '/images/exp-hiking.jpg',
      },
      {
        id: 'e2',
        title: 'Cata de vinos del Somontano',
        description: 'Sesión guiada con sumiller en nuestra bodega de piedra. Descubre los tintos y blancos premiados de la D.O. Somontano.',
        duration: '2 h',
        badge: '35 €/persona',
        imageUrl: '/images/exp-wine.jpg',
      },
      {
        id: 'e3',
        title: 'Observación astronómica nocturna',
        description: 'El cielo oscuro del Sobrarbe es uno de los mejores de Europa. Nuestro astrónomo local te guiará por la Vía Láctea con telescopio profesional.',
        duration: '2,5 h',
        badge: '45 €/persona',
        imageUrl: '/images/exp-stars.jpg',
      },
      {
        id: 'e4',
        title: 'Ritual de bienestar pirenaico',
        description: 'Masaje con aceites de lavanda del Pirineo, baño termal y envoltura de barro mineral. Una experiencia sensorial completa.',
        duration: '90 min',
        badge: '80 €/persona',
        imageUrl: '/images/exp-spa.jpg',
      },
    ],
  },
  breakfast: {
    eyebrow: 'Gastronomía',
    title: 'Un desayuno que es ya una experiencia en sí misma',
    description:
      'Cada mañana el comedor de vigas del siglo XVIII se convierte en un mercado de proximidad. Los productos viajan pocos kilómetros: los huevos llegan de la granja de Broto, el queso del Ager de Isábena y el jamón de cerdo negro de Benasque.',
    schedule: '8:00 — 10:30 h',
    included: true,
    highlights: [
      { id: 'bh1', icon: 'leaf',   text: 'Miel artesana del Sobrarbe y mermeladas caseras de temporada' },
      { id: 'bh2', icon: 'coffee', text: 'Café de especialidad de tueste local y infusiones de hierbas pirenaicas' },
      { id: 'bh3', icon: 'wheat',  text: 'Pan de masa madre horneado a diario con harina de espelta ecológica' },
    ],
    note: 'También disponible: media pensión (cena incluida) · Consulta con recepción.',
  },
  amenities: {
    categories: [
      {
        id: 'ac1',
        title: 'En la habitación',
        items: [
          { id: 'ai1', icon: 'wifi',         label: 'WiFi gratuito' },
          { id: 'ai2', icon: 'shower-head',  label: 'Baño privado' },
          { id: 'ai3', icon: 'flame',        label: 'Calefacción' },
          { id: 'ai4', icon: 'wind',         label: 'Ventilador' },
          { id: 'ai5', icon: 'tv',           label: 'Smart TV' },
          { id: 'ai6', icon: 'phone',        label: 'Teléfono' },
        ],
      },
      {
        id: 'ac2',
        title: 'En el alojamiento',
        items: [
          { id: 'ai7',  icon: 'utensils-crossed', label: 'Restaurante' },
          { id: 'ai8',  icon: 'book-open',        label: 'Biblioteca' },
          { id: 'ai9',  icon: 'dumbbell',         label: 'Zona fitness' },
          { id: 'ai10', icon: 'flower-2',         label: 'Spa & bienestar' },
          { id: 'ai11', icon: 'baby',             label: 'Zona infantil' },
          { id: 'ai12', icon: 'accessibility',    label: 'Accesible' },
        ],
      },
      {
        id: 'ac3',
        title: 'Exterior',
        items: [
          { id: 'ai13', icon: 'waves',          label: 'Jacuzzi exterior' },
          { id: 'ai14', icon: 'parking-square', label: 'Aparcamiento' },
          { id: 'ai15', icon: 'car',            label: 'Garaje privado' },
          { id: 'ai16', icon: 'paw-print',      label: 'Admite mascotas' },
          { id: 'ai17', icon: 'flower-2',       label: 'Jardín y terraza' },
          { id: 'ai18', icon: 'wifi',           label: 'WiFi en jardín' },
        ],
      },
    ],
  },
  reviews: {
    overallRating: '4.8',
    totalReviews: '127',
    items: [
      {
        id: 'rv1',
        quote: 'Una experiencia que supera cualquier expectativa. El desayuno con vistas a los picos del Pirineo, la atención del equipo y la autenticidad de cada detalle hacen de La Posada del Sobrarbe un lugar al que regresaremos cada año.',
        author: 'María G.',
        origin: 'Madrid',
        stars: 5,
        date: 'Octubre 2024',
      },
      {
        id: 'rv2',
        quote: 'Llevábamos años buscando un hotel rural así: con alma, con historia y sin renunciar al confort. Lo hemos encontrado en Aínsa. La habitación con chimenea y el spa de piedra son sencillamente perfectos.',
        author: 'Javier M.',
        origin: 'Barcelona',
        stars: 5,
        date: 'Septiembre 2024',
      },
    ],
  },
  practicalInfo: {
    items: [
      { id: 'pi1', icon: 'clock',       label: 'Check-in',            detail: 'A partir de las 15:00 h' },
      { id: 'pi2', icon: 'clock',       label: 'Check-out',           detail: 'Hasta las 12:00 h' },
      { id: 'pi3', icon: 'x-circle',    label: 'Cancelación',         detail: 'Gratuita hasta 48 h antes' },
      { id: 'pi4', icon: 'credit-card', label: 'Pago',                detail: 'Tarjeta, Bizum y efectivo' },
      { id: 'pi5', icon: 'globe',       label: 'Idiomas',             detail: 'Español, inglés, francés' },
      { id: 'pi6', icon: 'baby',        label: 'Bebés',               detail: 'Cuna disponible sin cargo' },
      { id: 'pi7', icon: 'paw-print',   label: 'Mascotas',            detail: 'Admitidas (pequeño tamaño)' },
      { id: 'pi8', icon: 'shield',      label: 'Licencia turística',  detail: 'HU-R-000123-A' },
    ],
  },
  location: {
    address: 'Plaza Mayor, 2 · 22330 Aínsa · Huesca, España',
    directions: [
      {
        id: 'd1',
        icon: 'car',
        title: 'En coche',
        content: 'Desde Zaragoza: A-23 hasta Barbastro, luego A-138 hasta Aínsa (aprox. 2 h). Parking gratuito para huéspedes.',
      },
      {
        id: 'd2',
        icon: 'bus',
        title: 'En autobús',
        content: 'Alosa opera líneas regulares desde Zaragoza, Huesca y Barbastro con parada en Aínsa.',
      },
      {
        id: 'd3',
        icon: 'plane',
        title: 'En avión',
        content: 'Aeropuerto de Zaragoza (ZAZ) a 165 km. Podemos organizar traslado privado. Consúltenos al reservar.',
      },
    ],
    nearbyPoi: [
      { id: 'p1', name: 'Casco histórico de Aínsa',   distance: '2 min a pie' },
      { id: 'p2', name: 'Parque Nacional de Ordesa',  distance: '35 km' },
      { id: 'p3', name: 'Cañón de Añisclo',           distance: '18 km' },
      { id: 'p4', name: 'Broto',                       distance: '20 km' },
      { id: 'p5', name: 'Benasque',                    distance: '55 km' },
      { id: 'p6', name: 'Boltaña',                     distance: '8 km' },
    ],
  },
  booking: {
    eyebrow: 'Reserva directa',
    title: 'Reserva con nosotros y ahorra',
    subtitle: 'Mejor precio garantizado al reservar directamente. Sin intermediarios.',
    cancelNote: 'Cancelación gratuita hasta 48 h antes de la llegada',
  },
  memberOffers: {
    eyebrow: 'Exclusivo Club LPMBE',
    title: 'Ventajas exclusivas para socios',
    offers: [
      {
        id: 'mo1',
        icon: 'gift',
        badge: 'Regalo',
        title: 'Bienvenida especial Club LPMBE',
        description: 'Los miembros del Club reciben a su llegada una cesta de bienvenida con productos artesanos del Sobrarbe: vino, miel, queso y conservas locales.',
        conditions: 'Válido para todas las reservas directas. Sujeto a disponibilidad.',
        isFeatured: true,
      },
      {
        id: 'mo2',
        icon: 'percent',
        badge: 'Descuento',
        title: '10 % de descuento en tratamientos de spa',
        description: 'Disfruta de todos nuestros rituales de bienestar con un descuento exclusivo para socios del Club LPMBE. Masajes, envolturas y circuito termal incluidos.',
        conditions: 'Descuento no acumulable con otras promociones. Reserva previa.',
        isFeatured: false,
      },
      {
        id: 'mo3',
        icon: 'sparkles',
        badge: 'Experiencia',
        title: 'Cata privada de vinos del Somontano',
        description: 'Sesión de maridaje exclusiva para miembros: dos horas con nuestro sumiller, tres D.O. del Pirineo y tabla de quesos artesanos.',
        conditions: 'Para grupos de hasta 4 personas. Disponible jueves y viernes.',
        isFeatured: false,
      },
    ],
  },
}
