/**
 * Generado automáticamente desde Search Console + backend actual.
 * Objetivo: recuperar SEO de URLs legacy (redirect) y limpiar basura (410 Gone).
 */

import {
  LEGACY_FICHA_ID_REDIRECTS,
  LEGACY_SEMAFORO_ID_REDIRECTS,
} from './legacy-seo-id-redirects.generated';

export { LEGACY_FICHA_ID_REDIRECTS, LEGACY_SEMAFORO_ID_REDIRECTS };

export const LEGACY_DIRECT_REDIRECTS: Record<string, string> = {
  '/ainsa': '/pueblos/ainsa',
  '/ainsa-3': '/pueblos/ainsa',
  '/ainsa-4': '/pueblos/ainsa',
  '/ainsa-5': '/pueblos/ainsa',
  '/andalucia/grazalema': '/pueblos/grazalema',
  '/aragon/rubielos-de-mora': '/pueblos/rubielos-de-mora',
  '/banos-de-la-encina': '/pueblos/banos-de-la-encina',
  '/berlanga-de-duero-ya-es-oficialmente-uno-de-los-pueblos-mas-bonitos-de-espana': '/noticias/berlanga-de-duero-ya-es-oficialmente-uno-de-los-pueblos-mas-bonitos-de-espana',
  '/blog': '/actualidad',
  '/castrillo-de-los-polvazares-2': '/pueblos/castrillo-de-los-polvazares',
  '/categoria-producto/libros': '/tienda',
  '/contact-us': '/contacto',
  '/cudillero': '/pueblos/cudillero',
  '/el-pirineo-catalan-y-sus-pueblos-mas-bonitos/bagergue': '/pueblos/bagergue',
  '/en': '/?lang=en',
  '/experiencias-public': '/experiencias',
  '/ficha-pueblo': '/pueblos',
  '/fr': '/?lang=fr',
  '/jerez-de-los-caballeros-ya-luce-como-uno-de-los-pueblos-mas-bonitos-de-espana': '/noticias/jerez-de-los-caballeros-ya-luce-como-uno-de-los-pueblos-mas-bonitos-de-espana',
  '/la-asociacion': '/el-sello/quienes-somos',
  '/mas-bonitos-de-los-pirineos': '/rutas/mas-bonitos-de-los-pirineos',
  '/morella': '/pueblos/morella',
  '/noticias-de-lospueblosmbe': '/actualidad',
  '/noticias-y-eventos': '/actualidad',
  '/peniscola': '/pueblos/peniscola',
  '/politica-cookies': '/cookies',
  '/poza-de-la-sal-pueblo-mas-bonito': '/pueblos/poza-de-la-sal',
  '/producto/guia-oficial-2024': '/tienda',
  '/producto/guia-oficial-2025': '/tienda',
  '/producto/hoodie-with-logo': '/tienda',
  '/producto/mapa-michelin': '/tienda',
  '/producto/pack-guia-mapa': '/tienda',
  '/puebla-de-sanabria': '/pueblos/puebla-de-sanabria',
  '/pueblos-bonitos-pirineos/anso': '/pueblos/anso',
  '/pueblos-del-sol-y-la-tramuntana': '/rutas/pueblos-del-sol-y-la-tramuntana',
  '/ruta-de-los-pueblos-celtas': '/rutas/ruta-de-los-pueblos-celtas',
  '/ruta-de-los-pueblos-encantados-2': '/rutas/ruta-de-los-pueblos-encantados-2',
  '/ruta-de-los-pueblos-nazaries': '/rutas/ruta-de-los-pueblos-nazaries',
  '/ruta-druidas-y-la-mar': '/rutas/ruta-druidas-y-la-mar',
  '/ruta-iberico-y-la-frontera': '/rutas/ruta-iberico-y-la-frontera',
  '/ruta-jucar-y-el-mediterraneo': '/rutas/ruta-jucar-y-el-mediterraneo',
  '/ruta-pueblos-alma-canaria': '/rutas/ruta-pueblos-alma-canaria',
  '/ruta-pueblos-alma-canaria/betancuria': '/pueblos/betancuria',
  '/ruta-pueblos-blanco-infinito/castellar-de-la-frontera': '/pueblos/castellar-de-la-frontera',
  '/ruta-pueblos-blanco-infinito/grazalema': '/pueblos/grazalema',
  '/ruta-pueblos-blanco-infinito/zahara': '/pueblos/zahara',
  '/ruta-pueblos-cuatro-reinos/vinuesa': '/pueblos/vinuesa',
  '/ruta-pueblos-de-los-cuatro-reinos': '/rutas/ruta-pueblos-de-los-cuatro-reinos',
  '/ruta-pueblos-del-blanco-infinito': '/rutas/ruta-pueblos-del-blanco-infinito',
  '/ruta-pueblos-iberico-frontera/olivenza': '/pueblos/olivenza',
  '/ruta-pueblos-orden-y-la-espada': '/rutas/ruta-pueblos-orden-y-la-espada',
  '/ruta-pueblos-reino-y-el-califato': '/rutas/ruta-pueblos-reino-y-el-califato',
  '/ruta-pueblos-senda-caballeros/ayllon': '/pueblos/ayllon',
  '/ruta-pueblos-senda-caballeros/monteagudo-de-las-vicarias': '/pueblos/monteagudo-de-las-vicarias',
  '/ruta-pueblos-senorio-y-la-corona': '/rutas/ruta-pueblos-senorio-y-la-corona',
  '/ruta-senda-de-los-caballeros': '/rutas/ruta-senda-de-los-caballeros',
  '/sajazarra-2': '/pueblos/sajazarra',
  '/san-martin-de-trevejo': '/pueblos/san-martin-de-trevejo',
  '/san-martin-de-trevejo-2': '/pueblos/san-martin-de-trevejo',
  '/santillana-del-mar': '/pueblos/santillana-del-mar',
  '/semaforo': '/mapa',
  '/suscripcion-newsletter': '/newsletter',
  '/tiendapueblos': '/tienda',
  '/tiendapueblos/inicio/42-guia-2021.html': '/tienda',
  '/carrito': '/tienda/carrito',
  '/categoria-producto/camisetas': '/tienda',
  '/wp-login.php': '/entrar',
  '/proxy-oauth': '/entrar',
  '/category/office': '/tienda',
  // Informe GSC "Duplicada: sin versión canónica" - regiones/pueblos legacy y tienda
  '/aragon/anso': '/pueblos/anso',
  '/aragon/cantavieja': '/pueblos/cantavieja',
  '/cantabria/barcena-mayor': '/pueblos/barcena-mayor',
  '/castilla-y-leon/frias': '/pueblos/frias',
  '/castilla-y-leon/penalba-de-santiago': '/pueblos/penalba-de-santiago',
  '/comunidad-foral-de-navarra/ujue': '/pueblos/ujue',
  '/comunidad-valenciana/vilafames': '/pueblos/vilafames',
  '/en/pueblos': '/pueblos',
  '/galicia/castro-caldelas': '/pueblos/castro-caldelas',
  '/la-rioja/viniegra-de-abajo': '/pueblos/viniegra-de-abajo',
  '/la-rioja/viniegra-de-arriba': '/pueblos/viniegra-de-arriba',
  '/medievo-en-estado-puro-al-sur-de-aragon/valderrobres': '/pueblos/valderrobres',
  '/principado-de-asturias/torazu': '/pueblos/torazu',
  '/tiendapueblos/11-camisetas': '/tienda',
  // Informe GSC "Rastreada: sin indexar" mar-2026
  '/castilla-y-leon/pedraza': '/pueblos/pedraza',
  '/santillana-del-mar-5': '/pueblos/santillana-del-mar',
  '/ruta-pueblos-castilla-eterna': '/rutas/ruta-pueblos-castilla-eterna',
  '/pueblos-bonitos-pirineos/roncal': '/pueblos/roncal',
  '/andalucia/nijar': '/pueblos/nijar',
};
export const LEGACY_EXPERIENCIAS_ID_REDIRECTS: Record<string, string> = {
  '0': '/experiencias',
  '10': '/pueblos/valderrobres',
  '12': '/pueblos/calaceite',
  '16': '/pueblos/morella',
  '19': '/pueblos/rubielos-de-mora',
  '23': '/pueblos/pedraza',
  '25': '/pueblos/alcala-del-jucar',
  '27': '/pueblos/vejer-de-la-frontera',
  '29': '/pueblos/llastres',
  '31': '/pueblos/cantavieja',
  '35': '/pueblos/el-castell-de-guadalest',
  '36': '/pueblos/vilafames',
  '38': '/pueblos/anento',
  '39': '/pueblos/almagro',
  '41': '/pueblos/barcena-mayor',
  '42': '/pueblos/alquezar',
  '50': '/pueblos/laguardia',
  '51': '/pueblos/torazu',
  '56': '/pueblos/capileira',
  '63': '/pueblos/puebla-de-sanabria',
  '65': '/pueblos/ujue',
  '87': '/pueblos/bagergue',
  '101': '/pueblos/monteagudo-de-las-vicarias',
  '113': '/pueblos/banos-de-la-encina',
  '115': '/pueblos/bulnes',
  '120': '/pueblos/nuevo-baztan',
  '130': '/pueblos/el-burgo-de-osma',
};
export const LEGACY_NOTICIA_ID_REDIRECTS: Record<string, string> = {
};
export const LEGACY_EXACT_GONE_PATHS: string[] = [
  '/10-anos-en-la-red',
  '/5-nuevos-municipios',
  '/about-us/our-team/emerson-anderson',
  '/acreditacion-de-nuevos-pueblos',
  '/acto-proclamacion-burgo-de-osma',
  '/alcazar',
  '/alerta-por-fuertes-vientos',
  '/ampudia-comillas-parauta-trevejo-y-trujillo-reciben-en-fitur-su-acreditacion-como-uno-de-los-nuevos-pueblos-mas-bonitos-de-espana',
  '/app',
  '/area-recreativa-de-arroyomolinos-la-playita',
  '/asamblea-nacional-2025',
  '/asamblea-regional-centro',
  '/asamblea-regional-norte',
  '/asamblea-regional-sur-2025',
  '/author',
  '/author/estefania/feed',
  '/author/turismosajazarragmail-com',
  '/benito-diaz-el-sarrujan-de-carmona',
  '/capilla-del-espiritu-santo-de-la-santa-casa-de-misericordia',
  '/carta-calidad.html',
  '/casa-familiar-luis-ram-de-viu-y-quinto',
  '/casa-museo-de-julian-gayarre',
  '/casa-natal-joaquin-sanchez-de-cutanda-y-miralles',
  '/casa-senorial-de-los-condes-de-mogrovejo-2',
  '/casas-en-los-pueblos-mbe',
  '/casas-senoriales-casco-antiguo',
  '/casas-senoriales-casco-antiguo-2',
  '/casco-historico-4',
  '/casco-historico-5',
  '/casco-historico-6',
  '/casco-historico-7',
  '/casco-historico-8',
  '/casco-historico-9',
  '/casona-de-los-sanchez-tagle',
  '/casonas-montanesas',
  '/castillo-de-castellar-de-la-frontera',
  '/castillo-de-culla',
  '/castillo-de-culla-2',
  '/castillo-de-trujillo',
  '/category/asambleas',
  '/category/eventos-importantes',
  '/category/noticias',
  '/category/premios',
  '/category/rutas',
  '/category/sin-categoria',
  '/cdn-cgi/l/email-protection',
  '/certificacion-',
  '/certificacion-nuevos-pueblos',
  '/conjunto-historico-10',
  '/conjunto-historico-4',
  '/conjunto-historico-7',
  '/conjunto-historico-8',
  '/cueva-mona-2',
  '/cueva-mona-via-ferrata',
  '/dia-de-los-pueblos-mas-bonitos',
  '/dia-de-los-pueblos-mas-bonitos-de-espana',
  '/dia-hermanamiento-pueblos-rioja',
  '/el-conjunto-historico-artistico',
  '/el-faro-de-cudillero',
  '/el-mirador-de-puentedey',
  '/el-pirineo-catalan',
  '/el-pirineo-catalan-y-sus-pueblos-mas-bonitos',
  '/el-pueblo-de-los-deseos',
  '/embalse-de-isabel-ii',
  '/en-construccion',
  '/en/eventos/exposicion-de-pintura-campo-abierto-de-manuel-manzorro',
  '/en/eventos/viii-campna-de-dinamizacion-comercial-comillas-vale-por-5',
  '/en/eventos/virgen-crespillera',
  '/en/noticias/horarios-otono-invierno',
  '/en/noticias/los-bonos-burgosma-superan-las-cifras-de-campanas-anteriores',
  '/en/noticias/mauraca-2024-en-capileira-1727175757',
  '/en/noticias/se-entregaron-los-premios-de-la-xlii-edicion-del-certamen-poetico-internacional-que-organiza-la-orden-literaria-francisco-de-quevedo',
  '/en/noticias/xxi-edicion-del-festival-caprichos-musicales-de-comillas',
  '/encuentro-de-los-pueblos-mas-bonitos-del-mundo',
  '/ermita-de-nuestra-senora-de-la-bienvenida',
  '/ermita-de-san-diego',
  '/ermita-de-sant-pelegrin',
  '/ermita-de-sant-pelegrin-2',
  '/ermita-de-santa-ana',
  '/ermita-del-remei',
  '/ermita-el-humilladero',
  '/ermita-y-puente-del-loreto',
  '/ermita-y-puente-del-loreto-2',
  '/ermitas-valverde-de-la-vera',
  '/escapada-romantica-en-aragon',
  '/escudo-villa-de-vinuesa',
  '/estancia-romantica-en-el-norte-de-aragon',
  '/ficha-privada-nueva',
  '/ficha-privada-nueva-2',
  '/fichalugarpanel',
  '/fitur-2026-calendario-actividades',
  '/fr/noticias/navidad-en-chinchon-1734083375',
  '/fr/noticias/villanueva-de-los-infantes-celebra-la-ruta-de-los-patios-con-unos-excelentes-resultados-en-su-primer-fin-de-semana',
  '/fuente-sobre-el-rio-jerga',
  '/guia-oficial-2024',
  '/historia-sobre-la-pinochada',
  '/iglesia-de-la-inmaculada',
  '/iglesia-de-nuestra-senora-de-la-anunciacion',
  '/iglesia-de-nuestra-senora-de-la-asuncion-2',
  '/iglesia-de-nuestra-senora-de-la-asuncion-siglo-xvi-2',
  '/iglesia-de-san-francisco-javier-si-glo-xviii',
  '/iglesia-de-sant-cristofol',
  '/iglesia-de-santa-maria',
  '/iglesia-de-santa-maria-del-castillo',
  '/iglesia-nuestra-senora-de-la-aurora',
  '/iglesia-parroquial-de-la-inmaculada-concepcion',
  '/iglesia-santa-ana',
  '/ilustre-d-pedro-jose-fonte-2',
  '/interno',
  '/jardin-de-los-pinsapos',
  '/la-boutique-del-cuento',
  '/la-calle-real-y-su-arquitectura-tradicional',
  '/la-carrasca',
  '/la-ex-colegiata-de-nuestra-senora-del-manzano',
  '/la-plaza-del-santo-cristo',
  '/la-ruta-nazari',
  '/leyenda-laguna-negra-la-tierra-de-alvargonzalez',
  '/leyenda-laguna-negra-la-tierra-de-alvargonzalez-3',
  '/leyenda-puente-bardo',
  '/linares-de-mora-nuevo-pueblo',
  '/login-callback-app',
  '/los-banos-termales',
  '/los-piques',
  '/los-sabores-de-banos-de-la-encina',
  '/medievo-al-sur-de-aragon',
  '/medievo-en-estado-puro-al-sur-de-aragon/valderrobres',
  '/michelin-mapa-lpmbe',
  '/mirador-de-cimadevilla',
  '/mirador-de-la-atalaya',
  '/mirador-del-naranjo',
  '/mirador-del-penayu',
  '/mirador-el-faro',
  '/monumento-a-la-vaca-tudanca',
  '/muelle-viejo',
  '/muralla-oeste-mirador-de-puertomingalvo',
  '/muralla-siglos-xiii-xiv',
  '/noche-',
  '/nota',
  '/noticias-y-eventos/6707',
  '/noticias-y-eventos/6713',
  '/noticias-y-eventos/6735',
  '/noticias-y-eventos/7251',
  '/noticias-y-eventos/7260',
  '/noticias-y-eventos/7263',
  '/noticias-y-eventos/7530',
  '/noticias/fiestas-ntra-sra-del-rosario',
  '/noticias/la-exposicion-tradicion-en-el-campo-de-montiel-coleccion-etnografica-del-hospital-de-santiago-se-inaugura-el-viernes-23-de-diciembre',
  '/noticias/mauraca-2024-en-capileira-1727175757',
  '/noticias/mercado-de-las-luces-en-chinchon',
  '/notifications',
  '/nueva-aplicacion-movil',
  '/nueva-incorporacion-de-pueblos',
  '/nuevo-semaforo-de-afluencia',
  '/nuevos-',
  '/nuevos-pueblos-2026',
  '/pagina-de-prueba-filtros',
  '/palacio-de-los-barreda-bracho-actual-parador-gil-blas-2',
  '/palacio-de-los-diaz-cossio-y-mier',
  '/palacio-peredo-barreda',
  '/palacio-valdivieso-actual-hotel-altamira',
  '/password-reset',
  '/pazo-de-baladron',
  '/penalosa-un-el-poblado-prehistorico-a-orillas-del-rumblar',
  '/pf/architecture-project',
  '/pf/business-consulting-3',
  '/pf/business-consulting-5',
  '/pf/business-consulting-6',
  '/pf/business-marketing-3',
  '/pf/human-resources',
  '/pf/human-resources-3',
  '/pf/industrial-growth-fund',
  '/pf/short-term-loans-2',
  '/pf/short-term-loans-3',
  '/pf/video-project',
  '/pf/villa-for-rent',
  '/pf/web-project',
  '/pino-escobon',
  '/pino-escobon-2',
  '/pino-escobon-area-recreativa',
  '/plaza-de-santo-domingo',
  '/plaza-divino-salvador',
  '/ponte-vella',
  '/ponte-vella-2',
  '/primeros-pueblos-de-espana',
  '/proclamacion-en-llerena',
  '/proclamacion-la-fresneda',
  '/projects-page',
  '/projects-page/our-projects',
  '/projects/architecture-project',
  '/projects/business-consulting-5',
  '/projects/business-consulting-6',
  '/projects/business-marketing-3',
  '/projects/human-resources-3',
  '/projects/industrial-growth-fund',
  '/projects/short-term-loans-3',
  '/projects/video-project',
  '/projects/villa-for-rent',
  '/projects/web-project',
  '/pueblo-nuevo-de-castellar-de-la-frontera',
  '/pueblo-semaforo',
  '/pueblos-bonitos-pirineos',
  '/puente-y-ermita-del-loreto',
  '/puentedey-burgos-acreditacion',
  '/puerta-del-calvario',
  '/puntos/la-atalaya.html',
  '/ruta-de-los-',
  '/ruta-pueblos-',
  '/ruta-pueblos-celtas',
  '/rutas-app',
  '/sa',
  '/sagrado-corazon-de-jesus',
  '/semaforo-test',
  '/semana-santa-en-los-pueblos',
  '/seminario-mayor',
  '/seminario-mayor-de-comillas',
  '/services/our-services/audit-evaluation',
  '/services/our-services/business-formation',
  '/services/our-services/consumer-markets',
  '/services/our-services/trades-and-stocks',
  '/sorteo-especial',
  '/sorteo-especial-redes-sociales',
  '/tag/pirineo-catalan',
  '/tag/pueblo-con-encanto',
  '/tag/pueblos-bonitos',
  '/tag/semana-santa',
  '/tag/viernes-santo',
  '/test',
  '/torre-vigia',
  '/um-login',
  '/un-castillo-de-pelicula',
  '/user/alexander',
  '/user/turismosajazarragmail-com',
  '/vistas-desde-la-torre-iglesia-de-san-agustin',
  // Informe GSC "404" mar-2026
  '/granero-del-comendador-posterior-carcel',
  '/moli-de-lorde-2',
  '/sueno-barroco',
  '/video-del-pueblo-de-los-deseos',
  '/pueblo----',
  '/santillana-del-mar-2',
  '/santillana-del-mar-3',
  '/casa-natal-de-joaquin-arnau-ibanez',
  '/dia-hermanamiento-pueblos-rioja',
  '/puentedey-burgos-acreditacion',
  '/register',
  '/notifications',
  '/ruta-druidas-mar/lierganes',
  '/ruta-pueblos-cuatro-reinos/viniegra-de-abajo',
  '/ruta-pueblos-reino-califato/banos-de-la-encina',
  '/ruta-pueblos-senorio-corona/pastrana',
  '/ruta-los-nazaries/nijar',
  '/michelin-mapa-lpmbe',
  '/politica-privacidad',
  '/2024-da-la-bienvenida-a-los-116-pueblos-mas-bonitos-de-espana-tras-la-incorporacion-de-ampudia-palencia-comillas-cantabria-parauta-malaga-trevejo-y-trujillo-caceres/ampudia',
  // Informe GSC "Rastreada: sin indexar" mar-2026
  '/alianza-msc-cruceros',
  '/asamblea-regional-este',
  '/atienza-barroca',
  '/barriada-de-la-almoraima',
  '/callejon-del-villar',
  '/capilla-de-nuestra-senora-de-las-nieves',
  '/casco-historico',
  '/casco-historico-2',
  '/casco-historico-3',
  '/conjunto-historico-6',
  '/conjunto-historico-9',
  '/culla',
  '/el-puente-de-los-vascos',
  '/ermita-de-santo-tome',
  '/ermita-san-roque',
  '/granero-del-comendador',
  '/iglesia-de-nuestra-senora-de-la-asuncion',
  '/iglesia-de-santa-maria-de-portor',
  '/iglesia-de-santa-maria-magdalena',
  '/iglesia-nueva-o-de-la-santisima-trinidad',
  '/mirador-de-san-roque',
  '/museo-de-arte-contemporaneo-de-genalguacil',
  '/palacio-de-sobrellano',
  '/paseando-por-el-medievo',
  '/plaza-de-la-comunidad',
  '/plaza-de-la-comunidad-2',
  '/pollentia-ciudad-romana',
  '/portada-de-la-iglesia-colegiata',
  '/projects/business-consulting-4',
  '/puente-medieval',
  '/recursos',
  '/santa-maria-del-castillo',
  '/test2',
  '/torre-del-reloj',
];
