import type { LandingConfig } from './comercio-config'

export const defaultConfig: LandingConfig = {
  hero: {
    eyebrow: 'Artesanía Premium · Club LPMBE',
    title: 'Quesos del Pirineo Pardo',
    tagline: 'Queso de oveja madurado en cueva · Sobrarbe, Aragón desde 1972',
    badges: [
      { text: 'Producto km0' },
      { text: 'Hecho a mano' },
      { text: 'Tradición familiar' },
      { text: 'Premio Quesos de España 2023' },
    ],
    slides: [
      { image: '/images/hero-1.jpg', alt: 'Quesos artesanos madurados en cueva' },
      { image: '/images/hero-2.jpg', alt: 'El pastor con las ovejas en los Pirineos' },
      { image: '/images/hero-3.jpg', alt: 'Interior del obrador tradicional' },
      { image: '/images/hero-4.jpg', alt: 'Cata de quesos en el obrador' },
    ],
    ctaPrimary: { text: 'Visita el obrador', href: '#reserva' },
    ctaSecondary: { text: 'Comprar online', href: '#productos' },
  },
  stats: [
    { value: '1972', label: 'Tres generaciones' },
    { value: '100%', label: 'Leche cruda de ovejas propias' },
    { value: '5', label: 'Quesos de temporada' },
    { value: '+200', label: 'Socios LPMBE han visitado' },
    { value: '24–48h', label: 'Envíos a península' },
  ],
  history: {
    eyebrow: 'El oficio',
    title: 'Tres generaciones de pastores y queseros',
    paragraphs: [
      'Todo comenzó en 1972, cuando el abuelo Pardo decidió transformar la leche de sus ovejas en algo extraordinario. En las laderas del Pirineo aragonés, donde el pasto crece lento y aromático, encontró el lugar perfecto para criar su rebaño.',
      'Hoy, tres generaciones después, seguimos haciendo las cosas igual que entonces: ordeño a mano al amanecer, cuajada natural con cuajo de cordero lechal, y maduración en la misma cueva de piedra que descubrió el abuelo.',
      'Cada pieza de queso lleva dentro cientos de amaneceres en la montaña, el saber de nuestros mayores, y el compromiso de mantener vivo un oficio que se resiste a desaparecer.',
    ],
    pullQuote: 'La cueva no se inventa. La cueva se hereda.',
    mainImage: '/images/history-main.jpg',
    photos: [
      { image: '/images/history-1972.jpg', year: '1972', alt: 'El abuelo Pardo con las primeras ovejas' },
      { image: '/images/history-1998.jpg', year: '1998', alt: 'Segunda generación en el obrador' },
      { image: '/images/history-2024.jpg', year: '2024', alt: 'La familia Pardo hoy' },
    ],
  },
  products: [
    {
      id: 'curado-cueva',
      name: 'Curado de Cueva',
      description: 'Nuestro queso insignia, madurado 6 meses en cueva natural',
      format: 'Pieza 700 g',
      price: 24,
      image: '/images/product-curado.jpg',
      badges: [{ text: 'Best-seller', variant: 'highlight' }],
      featured: true,
      availableOnline: true,
    },
    {
      id: 'semicurado',
      name: 'Semicurado Tradicional',
      description: 'Textura cremosa con 3 meses de maduración',
      format: 'Pieza 500 g',
      price: 16,
      image: '/images/product-semicurado.jpg',
      badges: [],
      availableOnline: true,
    },
    {
      id: 'añejo',
      name: 'Añejo Reserva',
      description: 'Intenso y complejo, 12 meses en cueva',
      format: 'Pieza 800 g',
      price: 32,
      image: '/images/product-anejo.jpg',
      badges: [{ text: 'Edición limitada', variant: 'new' }],
      availableOnline: true,
    },
    {
      id: 'fresco',
      name: 'Queso Fresco de Pastor',
      description: 'Suave y delicado, perfecto para ensaladas',
      format: 'Tarrina 250 g',
      price: 8,
      image: '/images/product-fresco.jpg',
      badges: [],
      availableOnline: false,
    },
    {
      id: 'trufa',
      name: 'Curado con Trufa Negra',
      description: 'Edición especial con trufa del Maestrazgo',
      format: 'Pieza 400 g',
      price: 28,
      image: '/images/product-trufa.jpg',
      badges: [{ text: 'Madurado 90 días' }],
      availableOnline: true,
    },
  ],
  process: [
    {
      number: 1,
      title: 'El pasto',
      description: 'Nuestras ovejas pastan libres en los prados de montaña, alimentándose de hierbas aromáticas que dan carácter único a la leche.',
      image: '/images/process-pasto.jpg',
    },
    {
      number: 2,
      title: 'El ordeño',
      description: 'Cada mañana, al amanecer, ordeñamos a mano para preservar todas las propiedades de la leche cruda.',
      image: '/images/process-ordeno.jpg',
    },
    {
      number: 3,
      title: 'La cuajada',
      description: 'Utilizamos cuajo natural de cordero lechal y técnicas transmitidas de generación en generación.',
      image: '/images/process-cuajada.jpg',
    },
    {
      number: 4,
      title: 'La cueva',
      description: 'La maduración en nuestra cueva natural, a temperatura y humedad constantes, da el toque final a cada pieza.',
      image: '/images/process-cueva.jpg',
    },
  ],
  obrador: {
    image: '/images/obrador-full.jpg',
    title: 'Nuestra cueva y obrador',
    description: 'Un espacio donde el tiempo se mide en maduraciones y las estaciones marcan el ritmo. Visítanos y descubre el lugar donde nacen nuestros quesos.',
    ctaText: 'Reserva una visita',
    ctaHref: '#reserva',
  },
  experiences: [
    {
      id: 'visita-cata',
      title: 'Visita guiada + cata',
      image: '/images/exp-visita.jpg',
      duration: '1h 30min',
      maxPeople: 12,
      priceFrom: 18,
      clubDiscount: 'Socios LPMBE −15%',
      available: true,
    },
    {
      id: 'taller-infantil',
      title: 'Taller infantil de queso',
      image: '/images/exp-taller.jpg',
      duration: '2h',
      maxPeople: 10,
      priceFrom: 12,
      available: true,
    },
    {
      id: 'cata-maridaje',
      title: 'Cata maridaje con vinos del Somontano',
      image: '/images/exp-maridaje.jpg',
      duration: '2h',
      maxPeople: 8,
      priceFrom: 35,
      clubDiscount: 'Socios LPMBE −15%',
      available: true,
    },
    {
      id: 'jornada-pastor',
      title: 'Un día como pastor',
      image: '/images/exp-pastor.jpg',
      duration: '6h',
      maxPeople: 4,
      priceFrom: 75,
      available: false,
    },
  ],
  awards: {
    awards: [
      { logo: '/images/award-qea.png', name: 'Quesos de España 2023' },
      { logo: '/images/award-aragon.png', name: 'Artesanía de Aragón' },
      { logo: '/images/award-slow.png', name: 'Slow Food' },
      { logo: '/images/award-ecologico.png', name: 'Certificación Ecológica' },
    ],
    pressQuotes: [
      { quote: 'Una de las mejores queserías de Aragón, donde tradición y excelencia se dan la mano.', source: 'El País Semanal', year: '2024' },
      { quote: 'El sabor de los Pirineos en cada bocado.', source: 'Guía Repsol', year: '2023' },
    ],
  },
  testimonials: [
    {
      id: '1',
      quote: 'Visitamos el obrador en familia y fue una experiencia inolvidable. Los niños no paraban de hacer preguntas y el queso... ¡espectacular!',
      name: 'María García',
      city: 'Zaragoza',
      rating: 5,
    },
    {
      id: '2',
      quote: 'Compro online desde hace años. La calidad siempre impecable y el envío rapidísimo. El añejo es mi favorito.',
      name: 'Carlos Fernández',
      city: 'Barcelona',
      rating: 5,
    },
    {
      id: '3',
      quote: 'Como socia del club LPMBE, he visitado muchos productores, pero este es especial. Se nota el amor por el oficio.',
      name: 'Elena Martínez',
      city: 'Madrid',
      rating: 5,
    },
    {
      id: '4',
      quote: 'La cata maridaje con vinos del Somontano fue una maravilla. Repetiremos seguro.',
      name: 'Javier López',
      city: 'Valencia',
      rating: 5,
    },
  ],
  practicalInfo: {
    schedule: [
      { days: 'Lunes a Sábado', hours: '10:00–14:00, 17:00–20:00' },
      { days: 'Domingo', hours: 'Cerrado' },
    ],
    paymentMethods: ['Efectivo', 'Tarjeta', 'Bizum'],
    shipping: {
      peninsula: '24–48h',
      islands: '4–6 días',
    },
    returns: '14 días para productos no perecederos',
    languages: ['Castellano', 'English', 'Català'],
  },
  location: {
    coordinates: { lat: 42.4167, lng: 0.1333 },
    address: 'Camino de la Cueva, 12',
    comarca: 'Sobrarbe',
    provincia: 'Huesca, Aragón',
    directions: {
      car: 'A 5 min del centro de Aínsa por la carretera de Boltaña',
      publicTransport: 'Bus desde Barbastro (línea Aínsa)',
      parking: 'Aparcamiento gratuito junto al obrador',
    },
    googleMapsUrl: 'https://maps.google.com/?q=42.4167,0.1333',
  },
  ctaReserva: {
    title: 'Visítanos en el obrador',
    subtitle: 'Descubre el proceso artesano, conoce a nuestras ovejas y degusta nuestros quesos',
    buttons: {
      reserva: { text: 'Reservar visita', href: '#experiencias' },
      llamar: { text: 'Llamar', href: 'tel:+34974500123' },
      whatsapp: { text: 'WhatsApp', href: 'https://wa.me/34974500123' },
    },
  },
  clubOffers: {
    eyebrow: 'Ventajas Club LPMBE',
    title: 'Beneficios exclusivos para socios',
    offers: [
      {
        id: '1',
        icon: 'percent',
        title: 'Descuento en visitas',
        highlight: '−15% en todas las experiencias',
        badge: 'destacada',
      },
      {
        id: '2',
        icon: 'truck',
        title: 'Envío gratuito',
        highlight: 'En pedidos superiores a 50€',
        badge: 'nueva',
      },
      {
        id: '3',
        icon: 'gift',
        title: 'Queso de bienvenida',
        highlight: 'Pieza de semicurado de regalo',
      },
    ],
  },
  socialLinks: [
    { platform: 'instagram', url: 'https://instagram.com/quesospirineo' },
    { platform: 'facebook', url: 'https://facebook.com/quesospirineo' },
    { platform: 'youtube', url: 'https://youtube.com/@quesospirineo' },
    { platform: 'tripadvisor', url: 'https://tripadvisor.com/quesospirineo' },
  ],
  clubCTA: {
    title: 'Forma parte del Club LPMBE',
    description: 'Únete a nuestra comunidad de amantes de los productos artesanos y disfruta de ventajas exclusivas, acceso prioritario a ediciones limitadas y mucho más.',
    ctaText: 'Hazte socio',
    ctaHref: '/club',
  },
}
