/**
 * Genera LEGACY_FICHA_ID_REDIRECTS y LEGACY_SEMAFORO_ID_REDIRECTS desde el API.
 * Uso: npx ts-node --esm scripts/generate-legacy-seo-ids.ts
 * O con API local: NEXT_PUBLIC_API_URL=http://localhost:3000 npx ts-node ...
 */
const API_BASE =
  process.env.NEXT_PUBLIC_API_URL?.replace(/\/$/, '') ||
  'https://lpmbe-backend-production.up.railway.app';

async function main() {
  const res = await fetch(`${API_BASE}/pueblos`);
  if (!res.ok) {
    console.error('Error fetching pueblos:', res.status);
    process.exit(1);
  }
  const pueblos = (await res.json()) as Array<{ id: number; slug: string }>;
  const ficha: Record<string, string> = {};
  const semaforo: Record<string, string> = {};
  for (const p of pueblos) {
    const id = String(p.id);
    ficha[id] = `/pueblos/${p.slug}`;
    semaforo[id] = `/pueblos/${p.slug}`;
  }
  console.log('// Generated by scripts/generate-legacy-seo-ids.ts - do not edit by hand');
  console.log('export const LEGACY_FICHA_ID_REDIRECTS: Record<string, string> = {');
  for (const [id, path] of Object.entries(ficha).sort((a, b) => Number(a[0]) - Number(b[0]))) {
    console.log(`  '${id}': '${path}',`);
  }
  console.log('};');
  console.log('export const LEGACY_SEMAFORO_ID_REDIRECTS: Record<string, string> = {');
  for (const [id, path] of Object.entries(semaforo).sort((a, b) => Number(a[0]) - Number(b[0]))) {
    console.log(`  '${id}': '${path}',`);
  }
  console.log('};');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
