export type Asistente = {
  acreditacion: string;
  delegacion: string;
  nombre: string;
  apellidos: string;
  dni: string;
  cargo: string;
  email: string;
  telefono: string;
  autobus: boolean;
  hotelCastellar: string;
  cenaMieCastellar: boolean;
  almuerzoJueCastellar: boolean;
  cenaJueVejer: boolean;
  hotelVejer: string;
  hotelVejerAsignado: string;
  almuerzoVieGrazalema: boolean;
  cenaVieGrazalema: boolean;
  almuerzoSabZahara: boolean;
  cenaSabSetenil: boolean;
  hotelGrazalema: string;
  hotelGrazalemaAsignado: string;
};

export type DelegacionResumen = {
  delegacion: string;
  tipo: string;
  totalAsistentes: number;
  enAutobus: number;
  necesitaTransfer: number;
  horaLlegada: string;
  horaPartida: string;
  alergias: string;
  observaciones: string;
};

export const ASISTENTES: Asistente[] = [
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Francisco', apellidos: 'MESTRE', dni: '', cargo: 'Président', email: 'franmestre@lospueblosmasbonitosdeespana.org', telefono: '667 628 720', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Manzanilla', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Esther', apellidos: 'AISA', dni: '', cargo: 'Vice-présidente', email: 'estheraisa@lospueblosmasbonitosdeespana.org', telefono: '633 976 027', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Manzanilla', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Pedro', apellidos: 'FERNÁNDEZ-ARROYO', dni: '', cargo: 'Resp. relations institutionnelles', email: 'pedro@lospueblosmasbonitosdeespana.org', telefono: '629 10 81 05', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Casa Uva', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Estefanía', apellidos: 'ABELLA', dni: '', cargo: 'Resp. marketing & communication', email: 'info@lospueblosmasbonitosdeespana.org', telefono: '604 86 10 18', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Manzanilla', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Alberto', apellidos: 'LOYO', dni: '', cargo: 'Resp. réseaux sociaux', email: 'socialmedia@lospueblosmasbonitosdeespana.org', telefono: '618 38 75 64', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Manzanilla', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Carlos', apellidos: 'OPPE', dni: '', cargo: 'Vice-président de la Commission Qualité', email: 'carlosoppe@lospueblosmasbonitosdeespana.org', telefono: '600 46 56 99', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Manzanilla', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Francisco Juan', apellidos: 'PERERA', dni: '', cargo: 'Président Région Sud / Maire de Tejeda', email: 'alcalde@tejeda.es', telefono: '630 61 28 80', autobus: true, hotelCastellar: 'DOBLE', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'DOBLE', hotelVejerAsignado: 'Manzanilla', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'DOBLE', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'no', delegacion: 'Los Pueblos más Bonitos de España', nombre: '(esposa Chicho)', apellidos: '', dni: '', cargo: 'acompañante', email: '', telefono: '', autobus: false, hotelCastellar: '', cenaMieCastellar: false, almuerzoJueCastellar: false, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Alfonso', apellidos: 'MARTÍNEZ', dni: '', cargo: 'Membre de la Commission Qualité', email: 'edicionesalfonsomartinez@gmail.com', telefono: '', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'La Casa del Califa', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Gemma', apellidos: 'PACHECO', dni: 'Gemma Pacheco Huecas 08992836C', cargo: 'Présidente Région Centre / Maire de Nuevo Baztán', email: 'gemap@ayto-nuevobaztan.es', telefono: '690 20 40 84', autobus: false, hotelCastellar: 'DOBLE', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'DOBLE 2 camas', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'DOBLE 2 camas', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Lola', apellidos: 'RUBIO', dni: 'María Dolores Rubio Berrio, 50057910C', cargo: 'Conseillère – Nuevo Baztán', email: '', telefono: '655 99 95 17', autobus: false, hotelCastellar: '', cenaMieCastellar: false, almuerzoJueCastellar: false, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Miguel Ángel', apellidos: 'ALONSO', dni: 'Miguel Ángel Alonso Saiz 13098666M', cargo: 'Président du Conseil de Puentedey', email: 'malonsosaiz@gmail.com', telefono: '630 21 66 00', autobus: false, hotelCastellar: 'DOBLE', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'DOBLE 2 camas', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'DOBLE 2 camas', hotelGrazalemaAsignado: 'La Casa de las Piedras' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Luis María', apellidos: 'LÓPEZ', dni: 'Luis María López Rojo 14584539D', cargo: 'Conseiller technique – Puentedey', email: '', telefono: '', autobus: false, hotelCastellar: '', cenaMieCastellar: false, almuerzoJueCastellar: false, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Carlos Javier', apellidos: 'GARCÍA', dni: '', cargo: 'Maire de Grazalema', email: '', telefono: '', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Javier', apellidos: 'PÉREZ', dni: '', cargo: 'Premier adjoint – Grazalema', email: '', telefono: '', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Adrián', apellidos: 'VACA', dni: '', cargo: 'Maire de Castellar de la Frontera', email: '', telefono: '', autobus: false, hotelCastellar: '', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'La Casa de las Piedras' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Marina', apellidos: 'SARAIBA', dni: '', cargo: 'Déléguée tourisme – Castellar', email: '', telefono: '', autobus: false, hotelCastellar: '', cenaMieCastellar: false, almuerzoJueCastellar: false, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Casa Shelly', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'La Casa de las Piedras' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Victoria Eugenia', apellidos: 'GONZÁLEZ', dni: '', cargo: 'Première adjointe – Castellar', email: '', telefono: '', autobus: false, hotelCastellar: '', cenaMieCastellar: false, almuerzoJueCastellar: false, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Rafael', apellidos: 'VARGAS', dni: '', cargo: 'Maire de Setenil de las Bodegas', email: '', telefono: '', autobus: false, hotelCastellar: '', cenaMieCastellar: false, almuerzoJueCastellar: true, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: true, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Virginia', apellidos: 'VILLALÓN', dni: '', cargo: 'Conseillère tourisme – Setenil', email: '', telefono: '', autobus: false, hotelCastellar: '', cenaMieCastellar: false, almuerzoJueCastellar: true, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Antonio', apellidos: 'GONZÁLEZ', dni: '', cargo: 'Maire de Vejer de la Frontera', email: '', telefono: '', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Ana', apellidos: 'GOMAR', dni: '', cargo: 'Resp. presse – Vejer', email: '', telefono: '', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Dominika', apellidos: 'PARADISO', dni: '', cargo: 'Déléguée tourisme – Vejer', email: '', telefono: '', autobus: false, hotelCastellar: '', cenaMieCastellar: false, almuerzoJueCastellar: false, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Isabel', apellidos: 'ROMERO', dni: '', cargo: 'Technicienne tourisme – Vejer', email: '', telefono: '', autobus: false, hotelCastellar: '', cenaMieCastellar: false, almuerzoJueCastellar: false, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Santiago', apellidos: 'GALVÁN', dni: 'SANTIAGO GALVÁN GÓMEZ 31719379X', cargo: 'Maire de Zahara', email: '', telefono: '', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: false, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Paqui', apellidos: 'BARRERA', dni: 'PAQUI BARRERA PINO 74929249X', cargo: 'Conseillère participation citoyenne – Zahara', email: '', telefono: '', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: false, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Zahara', apellidos: 'JARILLO', dni: 'VICENTE JARILLO RUIZ 25591349P', cargo: 'Conseiller tourisme – Zahara', email: '', telefono: '', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: false, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: '', hotelGrazalemaAsignado: '' },

  // Helène Ducros
  { acreditacion: 'sí', delegacion: 'Université de Caroline du Nord', nombre: 'Helene', apellidos: 'DUCROS', dni: '', cargo: 'Chercheuse en géographie humaine', email: 'helene@alumni.unc.edu', telefono: 'FR 0628292219', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },

  // Chófer
  { acreditacion: 'no', delegacion: 'Los Pueblos más Bonitos de España', nombre: 'Chófer', apellidos: '', dni: '', cargo: 'Chófer', email: '', telefono: '', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: false, almuerzoJueCastellar: false, cenaJueVejer: false, hotelVejer: 'INDIV', hotelVejerAsignado: 'Hotel La Janda', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },

  // Suiza
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages de Suisse', nombre: 'Alain', apellidos: 'SAINT-SULPICE', dni: '', cargo: 'Responsable Romandie', email: '', telefono: '', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Hotel V', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages de Suisse', nombre: 'Kevin', apellidos: 'QUATTROPANI', dni: '', cargo: 'Président', email: '', telefono: '', autobus: false, hotelCastellar: '', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages de Suisse', nombre: 'Christian', apellidos: 'GUERRA', dni: '', cargo: 'Resp. réseaux sociaux', email: 'beauxvillages@bluewin.ch', telefono: '', autobus: false, hotelCastellar: '', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },

  // Canadá
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages de Québec', nombre: 'Jonathan', apellidos: 'CHALIFOUX', dni: '', cargo: 'Président', email: 'maire@sasr.ca', telefono: '1-514-462-5027', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Hotel V', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },

  // Italia
  { acreditacion: 'sí', delegacion: "I Borghi più belli d'Italia", nombre: 'Fiorello', apellidos: 'PRIMI', dni: '', cargo: 'Président', email: 'fiorello.primi@tim.it', telefono: '+39 347 039 4800', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'La Casa del Califa', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: "I Borghi più belli d'Italia", nombre: 'Monica', apellidos: 'GILLOCCHI', dni: '', cargo: 'Communication et relations internationales', email: 'm.gillocchi@borghipiubelliditalia.it', telefono: '+39 338 615 1369', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'La Casa del Califa', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },
  { acreditacion: 'sí', delegacion: "I Borghi più belli d'Italia", nombre: 'Amato', apellidos: 'MERCURI', dni: '', cargo: 'Coordinateur Comité scientifique', email: 'a.mercuri@borghipiubelliditalia.it', telefono: '+39 333 873 9968', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'La Casa del Califa', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },
  { acreditacion: 'sí', delegacion: "I Borghi più belli d'Italia", nombre: 'Giuseppe', apellidos: 'SIMONE', dni: '', cargo: 'Vice-président', email: 'simongi@tiscali.it', telefono: '+39 339 873 2242', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'La Casa del Califa', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },
  { acreditacion: 'sí', delegacion: "I Borghi più belli d'Italia", nombre: 'Rosalba', apellidos: 'CARDINALE', dni: '', cargo: 'Vice-présidente', email: '', telefono: '+39 338 174 9435', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'La Casa del Califa', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },

  // Francia
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages de France', nombre: 'Alain', apellidos: 'DI STEFANO', dni: '', cargo: 'Président', email: 'adistefano@orange.fr', telefono: '+33 6 11 57 09 20', autobus: true, hotelCastellar: 'DOBLE', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'DOBLE', hotelVejerAsignado: 'Las Palmeras del Califa', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'DOBLE', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'no', delegacion: 'Les Plus Beaux Villages de France', nombre: '(acompañante)', apellidos: '', dni: '', cargo: 'Sra. Annick LE MENN', email: '', telefono: '', autobus: false, hotelCastellar: '', cenaMieCastellar: false, almuerzoJueCastellar: false, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages de France', nombre: 'Pascal', apellidos: 'BERNARD', dni: '', cargo: 'Chargé de qualité', email: 'pascal.bernard@lesplusbeauxvillagesdefrance.org', telefono: '+33 6 09 86 93 57', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Las Palmeras del Califa', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },

  // Valonia
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages de Wallonie', nombre: 'Alain', apellidos: 'COLLIN', dni: '', cargo: 'Président', email: 'alain4311@gmail.com', telefono: '+32 475 70 02 23', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Hotel V', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages de Wallonie', nombre: 'Gaston', apellidos: 'SCHREURS', dni: '', cargo: 'Vice-Président', email: 'gaston.schreurs@thimister-clermont.be', telefono: '+32 479 47 12 40', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Hotel V', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages de Wallonie', nombre: 'Hélène', apellidos: 'LEBRUN', dni: '', cargo: 'Administratrice', email: 'helene.lebrun@houyet.be', telefono: '+32 473 59 46 73', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Hotel V', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages de Wallonie', nombre: 'Aurélie', apellidos: 'DUCROZE', dni: '', cargo: 'Coordinatrice & chargée de projets', email: 'aurelie.ducroze@beauxvillages.be', telefono: '+32 495 88 34 26', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Hotel V', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages de Wallonie', nombre: 'Pierre-Henri', apellidos: 'ROLAND', dni: '', cargo: 'Chargé de Projets', email: 'tourisme@beauxvillages.be', telefono: '+32 479 55 14 10', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Hotel V', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },

  // Alemania
  { acreditacion: 'sí', delegacion: 'Sachsens Schönste Dörfer', nombre: 'Josef', apellidos: 'KEMPIS', dni: '', cargo: 'Président', email: 'kempis-oberc@gmx.de', telefono: '+27 76 642 5782', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Hotel V', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'La Casa de las Piedras' },
  { acreditacion: 'sí', delegacion: 'Sachsens Schönste Dörfer', nombre: 'Nico', apellidos: 'RITZ', dni: '', cargo: '', email: '', telefono: '+49 5681 994100', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Hotel V', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'La Casa de las Piedras' },
  { acreditacion: 'sí', delegacion: 'Villages historiques du Brandebourg', nombre: 'Dietmar', apellidos: 'ZIMMERMANN', dni: '', cargo: 'Président', email: 'dietmar.zimmermann@concordia.de', telefono: '+27 76 642 5782', autobus: false, hotelCastellar: 'DOBLE 2 camas', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'DOBLE', hotelVejerAsignado: 'Hotel V', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'DOBLE 2 camas', hotelGrazalemaAsignado: 'La Casa de las Piedras' },
  { acreditacion: 'sí', delegacion: 'Villages historiques du Brandebourg', nombre: 'Oleg', apellidos: 'KHIJNIAK', dni: '', cargo: 'Délégué', email: 'olegk@gmx.de', telefono: '+49 173 5832911', autobus: false, hotelCastellar: '', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: '', hotelGrazalemaAsignado: '' },

  // Japón
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages du Japon', nombre: 'Mami', apellidos: 'YODA', dni: '', cargo: 'Présidente par intérim', email: 'mamiyoda@gmail.com', telefono: '+81 90 5797 8862', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages du Japon', nombre: 'Takanobu', apellidos: 'MUKAI', dni: '', cargo: 'Secrétaire général', email: 't.mukai@utsukushii-mura.jp', telefono: '+81 80-3106-9457', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages du Japon', nombre: 'Ryunosuke', apellidos: 'TAKATSU', dni: '', cargo: 'Interprète', email: 'ryunosuketakatsu@gmail.com', telefono: '+81 70-8341-7175', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages du Japon', nombre: 'Haruki', apellidos: 'FURUKAWA', dni: '', cargo: 'Résidente village membre', email: 'haruki869docomo@icloud.com', telefono: '+81 80-2979-7950', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages du Japon', nombre: 'Koichi', apellidos: 'KINOSHITA', dni: '', cargo: 'Entreprise partenaire', email: 'rcrskoki@gmail.com', telefono: '+81 90-3196-5655', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages du Japon', nombre: 'Hiroki', apellidos: 'IMAEDA', dni: '', cargo: 'Entreprise partenaire', email: 'imaeda@chklab.com', telefono: '+81 90-3550-5498', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages du Japon', nombre: 'Mei', apellidos: 'IKEDA', dni: '', cargo: 'Entreprise partenaire', email: 'm-ikeda@chklab.com', telefono: '', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages du Japon', nombre: 'Riho', apellidos: 'TAKEZAWA', dni: '', cargo: 'Entreprise partenaire', email: 'takezawa@chklab.com', telefono: '+81 80-5248-7025', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages du Japon', nombre: 'Yukie', apellidos: 'IKEDA', dni: '', cargo: 'Soutien aux opérations', email: 'funky0giraffe19@gmail.com', telefono: '+81 80-1198-8442', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages du Japon', nombre: 'Teruyo', apellidos: 'MIYAZAKI', dni: '', cargo: 'Interprète', email: 'teruyospain@hotmail.com', telefono: '+34 658322596', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Convento San Francisco', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Horcajo' },

  // Líbano
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages du Liban', nombre: 'Maguy', apellidos: 'KOSTANIAN', dni: '', cargo: 'Présidente', email: 'maguy.k@pbvliban.org', telefono: '+961 3 701307 / +33 6 80056225', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Casa Shelly', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },

  // Bosnia
  { acreditacion: 'sí', delegacion: 'Les Plus Beaux Villages de Bosnie-Herzégovine', nombre: 'Sarah', apellidos: 'DEVISME', dni: '', cargo: 'Directrice Exécutive', email: 'sarahdevisme@hotmail.com', telefono: '+387 61 274 929', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Casa Uva', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },

  // China
  { acreditacion: 'sí', delegacion: 'The Most Beautiful Villages of China', nombre: 'Mingyuan', apellidos: 'SHE', dni: '', cargo: 'Secrétaire général', email: 'mingyuanshe1962@gmail.com', telefono: '0086-13716847589', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Casa Shelly', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: 'The Most Beautiful Villages of China', nombre: 'Yonghe', apellidos: 'WANG', dni: '', cargo: "Fondateur de l'Association", email: 'wyh@crebi.cn', telefono: '', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Casa Shelly', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },

  // Portugal
  { acreditacion: 'sí', delegacion: 'Aldeias Históricas de Portugal', nombre: 'Dalila', apellidos: 'DIAS', dni: '', cargo: 'Directrice exécutive', email: 'dalila.dias@aldeiashistoricasdeportugal.com', telefono: '961 673 805', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Casa Uva', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },
  { acreditacion: 'sí', delegacion: 'Aldeias Históricas de Portugal', nombre: 'Pilar', apellidos: 'REIS', dni: '', cargo: "Archéologue et membre de l'équipe", email: '', telefono: '', autobus: false, hotelCastellar: 'INDIV', cenaMieCastellar: true, almuerzoJueCastellar: true, cenaJueVejer: true, hotelVejer: 'INDIV', hotelVejerAsignado: 'Casa Uva', almuerzoVieGrazalema: true, cenaVieGrazalema: true, almuerzoSabZahara: true, cenaSabSetenil: true, hotelGrazalema: 'INDIV', hotelGrazalemaAsignado: 'Salinas' },

  // Traducción
  { acreditacion: 'sí', delegacion: 'Traducción', nombre: 'Vanessa', apellidos: 'BECH', dni: 'Vanessa Bech Dennis 25662661C', cargo: 'Interprète', email: '', telefono: '', autobus: false, hotelCastellar: 'DOBLE (cama matrimonio)', cenaMieCastellar: false, almuerzoJueCastellar: true, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Traducción', nombre: 'Kosuke', apellidos: 'NAKAMORI', dni: 'X0949910X', cargo: 'Interprète', email: '', telefono: '', autobus: true, hotelCastellar: 'INDIV', cenaMieCastellar: false, almuerzoJueCastellar: true, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Traducción', nombre: 'María de los Dolores', apellidos: 'SALIDO', dni: 'María de los Dolores Salido Rollan 33391588G', cargo: 'Interprète', email: '', telefono: '', autobus: false, hotelCastellar: 'DOBLE 2 CAMAS', cenaMieCastellar: false, almuerzoJueCastellar: true, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
  { acreditacion: 'sí', delegacion: 'Traducción', nombre: 'Leticia', apellidos: 'SÁNCHEZ', dni: 'Leticia Sánchez Balsalobre 48494817F', cargo: 'Interprète', email: '', telefono: '', autobus: false, hotelCastellar: '', cenaMieCastellar: false, almuerzoJueCastellar: true, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },

  // Técnicos cabinas
  { acreditacion: 'no', delegacion: 'Técnicos cabinas', nombre: 'Bernabé / Daniel', apellidos: 'BASSO / CUEVAS', dni: 'Bernabé Basso Karpeitschik 18512020X / Daniel Diego Cuevas Scowen 79025657A', cargo: 'Técnicos cabinas traducción', email: '', telefono: '', autobus: false, hotelCastellar: 'DOBLE 2 camas', cenaMieCastellar: false, almuerzoJueCastellar: true, cenaJueVejer: false, hotelVejer: '', hotelVejerAsignado: '', almuerzoVieGrazalema: false, cenaVieGrazalema: false, almuerzoSabZahara: false, cenaSabSetenil: false, hotelGrazalema: '', hotelGrazalemaAsignado: '' },
];

export const DELEGACIONES_RESUMEN: DelegacionResumen[] = [
  { delegacion: 'España', tipo: 'Activa', totalAsistentes: 13, enAutobus: 4, necesitaTransfer: 5, horaLlegada: '', horaPartida: '', alergias: 'Estefanía celíaca', observaciones: 'Ya están en Málaga, solo avisar de cuándo sale el transfer' },
  { delegacion: 'Les Plus Beaux Villages de Suisse', tipo: 'Activa', totalAsistentes: 3, enAutobus: 1, necesitaTransfer: 0, horaLlegada: '', horaPartida: '', alergias: '', observaciones: '' },
  { delegacion: 'Les Plus Beaux Villages de France', tipo: 'Activa', totalAsistentes: 3, enAutobus: 3, necesitaTransfer: 3, horaLlegada: '14:10', horaPartida: '14:35', alergias: '', observaciones: 'Avisar hora recogida aeropuerto. Le acompaña la Sra. Annick LE MENN' },
  { delegacion: 'Les Plus Beaux Villages de Wallonie', tipo: 'Activa', totalAsistentes: 5, enAutobus: 5, necesitaTransfer: 2, horaLlegada: '11:50', horaPartida: '10:15', alergias: '', observaciones: '' },
  { delegacion: "I Borghi più belli d'Italia", tipo: 'Activa', totalAsistentes: 5, enAutobus: 5, necesitaTransfer: 5, horaLlegada: '14:30', horaPartida: '15:15', alergias: 'Sr. Primi: no setas · Sra. Gillocchi: no pimienta negra', observaciones: '' },
  { delegacion: 'Les Plus Beaux Villages de Québec', tipo: 'Activa', totalAsistentes: 1, enAutobus: 1, necesitaTransfer: 0, horaLlegada: '', horaPartida: '', alergias: 'Cacahuetes', observaciones: '¿Viene finalmente la esposa?' },
  { delegacion: 'Les Plus Beaux Villages du Japon', tipo: 'Activa', totalAsistentes: 10, enAutobus: 10, necesitaTransfer: 10, horaLlegada: 'Varios días (18–20 mayo)', horaPartida: 'Varios horarios', alergias: 'Alergia a aguacate y marisco (Hiroki Imaeda)', observaciones: 'Se les convoca a las 15h para transfer aeropuerto' },
  { delegacion: 'Les Plus Beaux Villages de Bosnie-Herzégovine', tipo: 'Observadora', totalAsistentes: 1, enAutobus: 1, necesitaTransfer: 1, horaLlegada: '14:05', horaPartida: '13:50', alergias: '', observaciones: '' },
  { delegacion: 'The Most Beautiful Villages of China', tipo: 'Observadora', totalAsistentes: 2, enAutobus: 2, necesitaTransfer: 2, horaLlegada: '12:45', horaPartida: '12:35', alergias: '', observaciones: '' },
  { delegacion: 'Alemania (Sachsen + Brandebourg)', tipo: 'Observadora', totalAsistentes: 4, enAutobus: 1, necesitaTransfer: 0, horaLlegada: '', horaPartida: '', alergias: '', observaciones: '' },
  { delegacion: 'Les Plus Beaux Villages du Liban', tipo: 'Observadora', totalAsistentes: 1, enAutobus: 1, necesitaTransfer: 1, horaLlegada: '16:55', horaPartida: '11:50', alergias: '', observaciones: '' },
  { delegacion: 'Aldeias Históricas de Portugal', tipo: 'Invitada', totalAsistentes: 2, enAutobus: 2, necesitaTransfer: 0, horaLlegada: '', horaPartida: '', alergias: '', observaciones: '' },
  { delegacion: 'Helène Ducros (Universidad)', tipo: 'Universidad', totalAsistentes: 1, enAutobus: 1, necesitaTransfer: 0, horaLlegada: '13:20', horaPartida: '09:55', alergias: '', observaciones: '' },
  { delegacion: 'Castellar de la Frontera', tipo: 'Pueblo anfitrión', totalAsistentes: 4, enAutobus: 0, necesitaTransfer: 0, horaLlegada: '', horaPartida: '', alergias: '1 intolerante a la lactosa (Victoria, cena viernes Grazalema, almuerzo sábado Zahara, cena sábado Setenil)', observaciones: '' },
  { delegacion: 'Intérpretes + técnicos', tipo: '', totalAsistentes: 5, enAutobus: 0, necesitaTransfer: 0, horaLlegada: '', horaPartida: '', alergias: '', observaciones: '' },
];
